In [12]:
import sqlite3
import pandas as pd

DB_PATH = 'escola_v2.db'  # Caminho para o banco de dados SQLite

In [21]:
def executar_query(sql_query):
    try:
        conn = sqlite3.connect(DB_PATH)
        df_resultado = pd.read_sql_query(sql_query, conn)
        conn.close()
        return df_resultado
    except Exception as e:
        print("Erro:", e)

# Exercicios

1) Filltrar Alunos que moram em São Paulo
2) Filtrar Alunos que começam com C
3) Filtrar Cursos que custam entre 300 e 500
4) Filtrar Matriculas que estão Ativas ou Concluídas

In [ ]:
select *
from matriculas where status IN ('ativo', 'concluido');

In [27]:
consulta = """ 
SELECT name 
FROM sqlite_schema 
WHERE type='table';
"""
executar_query(consulta)
#show tables;

         name
0      alunos
1      cursos
2  matriculas

In [49]:
alunos_sp_query = """
BEGIN TRANSACTION;
"""
executar_query(alunos_sp_query)

Empty DataFrame
Columns: [id_aluno, nome, email, cidade, data_nascimento]
Index: []

In [ ]:
alunos_sp_query = """
INSERT INTO alunos (nome, idade, cidade, estado)
VALUES ('Carlos Silva', 22, 'São Paulo', 'SP');
"""
executar_query(alunos_sp_query)

alunos_sp_query = """
INSERT INTO alunos (nome, idade, cidade, estado)
VALUES ('Carlos Silva', 22, 'São Paulo', 'SP');
"""
executar_query(alunos_sp_query)

alunos_sp_query = """
INSERT INTO alunos (nome, idade, cidade, estado)
VALUES ('Carlos Silva', 22, 'São Paulo', 'SP');
"""
executar_query(alunos_sp_query)
alunos_sp_query = """
SELECT * FROM alunos
"""
executar_query(alunos_sp_query)

In [ ]:
commit_query = """
ROLLBACK;
"""
executar_query(commit_query)

In [3]:
# EXERCÍCIO 1: Filtragem Exata 
q1 = """
SELECT * FROM alunos 
WHERE cidade = 'São Paulo'
"""

print(executar_query(q1))

--- Alunos de SP ---

   id_aluno        nome            email     cidade data_nascimento
0         1   Ana Silva    ana@email.com  São Paulo      1995-03-10
1         3  Carla Diaz  carla@email.com  São Paulo      1998-07-15

In [ ]:
SELECT * FROM cursos 
WHERE precos_mensal BEETWEEN 300 AND 500;

In [54]:
# EXERCÍCIO 2: Filtragem por nome iniciando com 'C'
q2 = """
SELECT * FROM alunos 
WHERE nome LIKE 'C%'
"""

print(executar_query(q2))

   id_aluno        nome            email     cidade data_nascimento
0         3  Carla Diaz  carla@email.com  São Paulo      1998-07-15

In [59]:
# EXERCÍCIO 3: Intervalo de Preço
q3 = """
SELECT * FROM cursos 
WHERE preco_mensal BETWEEN 320 AND 400;
"""

executar_query(q3)

   id_curso nome_curso          nivel  preco_mensal
0       103   Espanhol  Intermediário         350.0
1       104    Francês         Básico         320.0

In [61]:
# EXERCÍCIO 4: Usando IN (Lista de Opções)
q4 = """
SELECT * FROM matriculas 
WHERE status IN ('Ativo', 'Concluido');
"""

print(executar_query(q4))

   id_matricula  id_aluno  id_curso data_matricula     status  nota_final
0          1001         1       101     2023-01-15      Ativo         8.5
1          1002         1       104     2023-02-20      Ativo         9.0
2          1004         3       101     2023-03-01      Ativo         7.8
3          1005         4       103     2023-01-20  Concluido        10.0
4          1006         5       101     2023-02-15      Ativo         6.5