# Installs 

pip install sqlalchemy

pip install psycopg2
(ou pip install psycopg2-binary)

pip install trino

In [45]:
import pandas as pd
from sqlalchemy import create_engine, text


# 1. Configurando a conexão com o Postgres no Docker
connection_string = 'postgresql://postgres:senha123@localhost:5432/postgres'
engine = create_engine(connection_string)

In [25]:
# 2. Criando um DataFrame simples
df_teste = pd.DataFrame({
    'id': [1, 2, 3, 5],
    'nome': ['Ana', 'Gustavo', 'Henrique', 'Patrik'],
    'cargo': ['CEO', 'Analista', 'Gerente de Projetos', 'Chefe']
})
df_teste

   id      nome                cargo
0   1       Ana                  CEO
1   2   Gustavo             Analista
2   3  Henrique  Gerente de Projetos
3   5    Patrik                Chefe

In [47]:
cursor = engine.connect()
cursor.execute(text('''TRUNCATE TABLE funcionarios''' ))
cursor.close()

In [39]:
# 3. Escrevendo no Banco
df_teste.to_sql('funcionarios', 
                engine, 
                if_exists='replace', 
                index=False)

4

In [40]:
# 4. Select dados
df_lido = pd.read_sql(
    "SELECT * FROM funcionarios", 
    engine)
df_lido

   id      nome                cargo
0   1       Ana                  CEO
1   2   Gustavo             Analista
2   3  Henrique  Gerente de Projetos
3   5    Patrik                Chefe