In [84]:
from transformers import pipeline
import pandas as pd
import numpy as np

In [66]:
model_leve = "./modelo_sentimento_offline"

analisador_leve = pipeline(
    "sentiment-analysis", 
    model=model_leve, 
    tokenizer=model_leve
)

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2689.85it/s, Materializing param=pre_classifier.weight]

In [70]:
frase = 'pode melhorar esse produto, nada de mais'
analisador_leve(frase)

[{'label': 'positive', 'score': 0.552482008934021}]

In [13]:
frase = "O atendimento foi péssimo, demoraram muito!"
resultado = analisador_leve(frase)

print(f"Texto: {frase}")
print(f"Resultado: {resultado}")

Texto: O atendimento foi péssimo, demoraram muito!
Resultado: [{'label': 'negative', 'score': 0.9028820991516113}]

In [49]:
reviews = pd.read_csv('review.csv')
reviews

   id_cliente                                              texto
0           1             Adorei o produto, chegou super rápido!
1           2          Não comprem, é uma fraude. Veio quebrado.
2           3  O produto é ok, cumpre o que promete, mas é caro.
3           4                Suporte horrível, nunca mais volto.
4           5            Excelente qualidade, recomendo a todos.

In [ ]:
def analisar_completo(text):
    retorno = analisador_leve(text)
    return [
        retorno[0]['label'], retorno[0]['score']
    ]

reviews[['sentimento', 'score']] = reviews['texto']\
    .apply(lambda x: pd.Series(\
        analisar_completo(x)
    ))

In [80]:
# Tentativa Ana
reviews = pd.read_csv('review.csv')
reviews

   id_cliente                                              texto
0           1             Adorei o produto, chegou super rápido!
1           2          Não comprem, é uma fraude. Veio quebrado.
2           3  O produto é ok, cumpre o que promete, mas é caro.
3           4                Suporte horrível, nunca mais volto.
4           5            Excelente qualidade, recomendo a todos.

In [86]:
reviews["score"] = np.nan
reviews["sentimento"] = np.nan

In [ ]:
for index, row in reviews.iterrows():
    try:
        scores = analisador_leve(row['texto'])
        reviews.loc[index, 'sentimento'] = scores[0]['label']
        reviews.loc[index, 'score'] = scores[0]['score']
    except:
        print("ERROR")
        raise Exception

id_cliente                                         1
texto         Adorei o produto, chegou super rápido!
score                                            NaN
sentimento                                       NaN
Name: 0, dtype: object
[{'label': 'positive', 'score': 0.9687928557395935}]
id_cliente                                            2
texto         Não comprem, é uma fraude. Veio quebrado.
score                                               NaN
sentimento                                          NaN
Name: 1, dtype: object
[{'label': 'negative', 'score': 0.8234622478485107}]
id_cliente                                                    3
texto         O produto é ok, cumpre o que promete, mas é caro.
score                                                       NaN
sentimento                                                  NaN
Name: 2, dtype: object
[{'label': 'positive', 'score': 0.8387840390205383}]
id_cliente                                      4
texto         Suporte horrível, nunca mais volto.
score                                         NaN
sentimento                                    NaN
Name: 3, dtype: object
[{'label': 'negative', 'score': 0.49617695808410645}]
id_cliente                                          5
texto         Excelente qualidade, recomendo a todos.
score                                             NaN
sentimento                                        NaN
Name: 4, dtype: object
[{'label': 'positive', 'score': 0.9922577738761902}]

/var/folders/hr/hf99z3sn635_fs6qx5t20m340000gn/T/ipykernel_91308/2547917450.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'positive' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  reviews.loc[index, 'sentimento'] = scores[0]['label']

In [93]:
reviews

,id_cliente,texto,score,sentimento
0,1,"Adorei o produto, chegou super rápido!",0.968793,positive
1,2,"Não comprem, é uma fraude. Veio quebrado.",0.823462,negative
2,3,"O produto é ok, cumpre o que promete, mas é caro.",0.838784,positive
3,4,"Suporte horrível, nunca mais volto.",0.496177,negative
4,5,"Excelente qualidade, recomendo a todos.",0.992258,positive

In [50]:
def analisar_sentimento(texto, model=analisador_leve):
    resultado = model(texto)
    return resultado[0]['label']

In [51]:
reviews['sentimento'] = reviews['texto'].apply(analisar_sentimento)

In [35]:
reviews['sentimento'] = reviews['texto'].apply(lambda x: analisador_leve(x)[0]['label'])

In [52]:
reviews

   id_cliente                                              texto sentimento
0           1             Adorei o produto, chegou super rápido!   positive
1           2          Não comprem, é uma fraude. Veio quebrado.   negative
2           3  O produto é ok, cumpre o que promete, mas é caro.   positive
3           4                Suporte horrível, nunca mais volto.   negative
4           5            Excelente qualidade, recomendo a todos.   positive

In [53]:
reviews.loc[5, 'texto'] = "Comum, nada fora do normal, igual outros."
reviews.loc[5, 'id_cliente'] = 6

In [57]:
reviews['sentimento'] = reviews['texto'].apply(analisar_sentimento)
reviews

   id_cliente                                              texto sentimento
0         1.0             Adorei o produto, chegou super rápido!   positive
1         2.0          Não comprem, é uma fraude. Veio quebrado.   negative
2         3.0  O produto é ok, cumpre o que promete, mas é caro.   positive
3         4.0                Suporte horrível, nunca mais volto.   negative
4         5.0            Excelente qualidade, recomendo a todos.   positive
5         6.0          Comum, nada fora do normal, igual outros.    neutral